trigger:
- experiment/pipeline

pool:
  vmImage: vs2017-win2016

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  solution: 'EarTrumpet.vs15.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'
  prebuild.sign-eartrumpet: 'azuresigntool sign -kvu https://withinnetwork.vault.azure.net -fd sha256 -kvi "$(keyvault.clientid)" -kvs "$(keyvault.secret)" -kvc "$(keyvault.certificates.selfsigned.name)" -tr "$(keyvault.services.timestamp)" Build/$(buildConfiguration)/Eartrumpet.exe'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Install NuGet Tooling'

- task: DotNetCoreCLI@2
  displayName: 'Install AzureSignTool'
  inputs:
    command: custom
    custom: 'tool'
    arguments: 'install --tool-path . azuresigntool'

- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  displayName: 'Set Bugsnag API Key'
  inputs:
   targetType: inline
   script: |
     $cfg = Get-Content ".\EarTrumpet\app.config"
     $cfg | ForEach-Object { $_.Replace("{bugsnag.apikey}", "$(bugsnag.apikey)") } | Set-Content ".\EarTrumpet\app.config"

- task: MSBuild@1
  displayName: 'Build EarTrumpet packages'
  inputs:
    solution: 'EarTrumpet.Package\\EarTrumpet.Package.wapproj'
    platform: 'x86'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:PreBuildEvent="$(prebuild.sign-eartrumpet)" /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)" /p:AppxPackageSigningEnabled=true /p:UapAppxPackageBuildMode=Sideload'
    maximumCpuCount: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Packages'